# Generated by Django 4.2.5 on 2023-12-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity_available',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
